# data pulled from dariusk's[1] corpora[2] project

# [1] http://tinysubversions.com/
# [2] https://github.com/dariusk/corpora

rooms = [ 
"aerary",
"aircraft cabin",
"airport lounge",
"alcove",
"anatomical theatre",
"anechoic chamber",
"antechamber",
"anteroom",
"armory",
"assembly room",
"atelier",
"attic",
"auditorium",
"backroom",
"ballroom",
"basement",
"bathroom",
"bedroom",
"billiard room",
"boardroom",
"boiler room",
"boudoir",
"breakfast nook",
"breezeway",
"cabin",
"cafeteria",
"caldarium",
"cellar",
"changing room",
"chapel",
"classroom",
"clean room",
"cloakroom",
"closet",
"cold room",
"common room",
"computer lab",
"conference room",
"conservatory",
"control room",
"conversation pit",
"corner office",
"courtroom",
"cry room",
"darkroom",
"den",
"dining room",
"dormitory",
"drawing room",
"dressing room",
"electrical room",
"emergency room",
"engine room",
"equipment room",
"fallout shelter",
"family room",
"fitting room",
"foyer",
"game room",
"garage",
"guest room",
"gym",
"hotel room",
"kitchen",
"laundry room",
"library",
"living room",
"lobby",
"locker room",
"loft",
"lounge",
"mailroom",
"map room",
"motel room",
"mud room",
"newsroom",
"nursery",
"office",
"panic room",
"pantry",
"parlor",
"playroom",
"pool room",
"print room",
"rec room",
"salon",
"sauna",
"schoolroom",
"showroom",
"sitting room",
"staff room",
"stockroom",
"storm cellar",
"studio",
"study",
"sunroom",
"tearoom",
"throne room",
"transmission control room",
"tv room",
"utility room",
"waiting room",
"washroom",
"water closet",
"weight room",
"wine cellar",
"wiring closet",
"workshop"
]

herbs = [
    "Angelica",
    "Basil",
    "Holy Basil",
    "Thai Basil",
    "Bay leaf",
    "Indian Bay leaf",
    "Boldo",
    "Borage",
    "Chervil",
    "Chives",
    "Garlic Chives",
    "Cicely",
    "Coriander leaf",
    "Cilantro",
    "Bolivian Coriander",
    "Vietnamese Coriander",
    "Culantro",
    "Cress",
    "Curry leaf",
    "Dill",
    "Epazote",
    "Hemp",
    "Hoja santa",
    "Houttuynia cordata",
    "Hyssop",
    "Jimbu",
    "Kinh gioi",
    "Lavender",
    "Lemon balm",
    "Lemon grass",
    "Lemon myrtle",
    "Lemon verbena",
    "Limnophila aromatica",
    "Lovage",
    "Marjoram",
    "Mint",
    "Mugwort",
    "Mitsuba",
    "Oregano",
    "Parsley",
    "Perilla",
    "Rosemary",
    "Rue",
    "Sage",
    "Savory",
    "Sansho",
    "Shiso",
    "Sorrel",
    "Tarragon",
    "Thyme",
    "Woodruff"
]

spices = [
    "Aonori",
    "Ajwain",
    "Allspice",
    "Amchoor",
    "Anise",
    "Star Anise",
    "Asafoetida",
    "Camphor",
    "Caraway",
    "Cardamom",
    "Black Cardamom",
    "Cassia",
    "Celery powder",
    "Celery seed",
    "Charoli",
    "Chenpi",
    "Cinnamon",
    "Clove",
    "Coriander seed",
    "Cubeb",
    "Cumin",
    "Nigella sativa",
    "Bunium persicum",
    "Dill",
    "Dill seed",
    "Fennel",
    "Fenugreek",
    "Fingerroot",
    "Greater Galangal",
    "Lesser Galangal",
    "Garlic",
    "Ginger",
    "Aromatic Ginger",
    "Golpar",
    "Grains of Paradise",
    "Grains of Selim",
    "Horseradish",
    "Juniper berry",
    "Kokum",
    "Korarima",
    "Dried Lime",
    "Liquorice",
    "Litsea cubeba",
    "Mace",
    "Mango-ginger",
    "Mastic",
    "Mahlab",
    "Black Mustard",
    "Brown Mustard",
    "White Mustard",
    "Nigella",
    "Njangsa",
    "Nutmeg",
    "Alligator Pepper",
    "Brazilian Pepper",
    "Chili Pepper",
    "Cayenne pepper",
    "Paprika",
    "Long Pepper",
    "Peruvian Pepper",
    "East Asian Pepper",
    "Sichuan Pepper",
    "Sansho",
    "Tasmanian Pepper",
    "Black Peppercorn",
    "Green Peppercorn",
    "White Peppercorn",
    "Pomegranate seed",
    "Poppy seed",
    "Radhuni",
    "Rose",
    "Saffron",
    "Salt",
    "Sarsaparilla",
    "Sassafras",
    "Sesame",
    "Shiso",
    "Sumac",
    "Tamarind",
    "Tonka bean",
    "Turmeric",
    "Uzazi",
    "Vanilla",
    "Voatsiperifery",
    "Wasabi",
    "Yuzu",
    "Zedoary",
    "Zereshk",
    "Zest"
]

vegetables = [
    "acorn squash",
    "alfalfa sprout",
    "amaranth",
    "anise",
    "artichoke",
    "arugula",
    "asparagus",
    "aubergine",
    "azuki bean",
    "banana squash",
    "basil",
    "bean sprout",
    "beet",
    "black bean",
    "black-eyed pea",
    "bok choy",
    "borlotti bean",
    "broad beans",
    "broccoflower",
    "broccoli",
    "brussels sprout",
    "butternut squash",
    "cabbage",
    "calabrese",
    "caraway",
    "carrot",
    "cauliflower",
    "cayenne pepper",
    "celeriac",
    "celery",
    "chamomile",
    "chard",
    "chayote",
    "chickpea",
    "chives",
    "cilantro",
    "collard green",
    "corn",
    "corn salad",
    "courgette",
    "cucumber",
    "daikon",
    "delicata",
    "dill",
    "eggplant",
    "endive",
    "fennel",
    "fiddlehead",
    "frisee",
    "garlic",
    "gem squash",
    "ginger",
    "green bean",
    "green pepper",
    "habanero",
    "herbs and spice",
    "horseradish",
    "hubbard squash",
    "jalapeno",
    "jerusalem artichoke",
    "jicama",
    "kale",
    "kidney bean",
    "kohlrabi",
    "lavender",
    "leek ",
    "legume",
    "lemon grass",
    "lentils",
    "lettuce",
    "lima bean",
    "mamey",
    "mangetout",
    "marjoram",
    "mung bean",
    "mushroom",
    "mustard green",
    "navy bean",
    "new zealand spinach",
    "nopale",
    "okra",
    "onion",
    "oregano",
    "paprika",
    "parsley",
    "parsnip",
    "patty pan",
    "pea",
    "pinto bean",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "rhubarb",
    "rosemary",
    "runner bean",
    "rutabaga",
    "sage",
    "scallion",
    "shallot",
    "skirret",
    "snap pea",
    "soy bean",
    "spaghetti squash",
    "spinach",
    "squash",
    "sweet potato",
    "tabasco pepper",
    "taro",
    "tat soi",
    "thyme",
    "topinambur",
    "tubers",
    "turnip",
    "wasabi",
    "water chestnut",
    "watercress",
    "white radish",
    "yam",
    "zucchini"
]
